# Generated by Django 4.0 on 2023-06-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('piso', models.CharField(max_length=1)),
                ('tipo', models.CharField(default='Simple', max_length=25)),
                ('precio', models.FloatField()),
                ('estado', models.CharField(default='Libre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.IntegerField()),
                ('procedencia', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
