# Generated by Django 4.0 on 2023-06-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['piso', 'numero']},
        ),
    ]
